apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minimesh.fullname" . }}-config
  labels:
    {{- include "minimesh.labels" . | nindent 4 }}
data:
  CONTROL_PLANE_ADDRESS: {{ include "minimesh.fullname" . }}-control-plane:{{ .Values.controlPlane.streamPort }}
  REGISTRY_ADDRESS: http://{{ include "minimesh.fullname" . }}-control-plane:{{ .Values.controlPlane.registryPort }}
  REGISTRATION_TTL: {{ .Values.sidecar.registrationTTL | quote }}
